<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Local Radio Stream</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@3.4.1/dist/tailwind.min.css">
  <link rel="stylesheet" href="/assets/css/style.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>
<body class="bg-gray-900 text-white min-h-screen flex flex-col items-center justify-center p-4 sm:p-6 md:p-8" data-csrf-token="<?php echo isset($csrf_token) ? htmlspecialchars($csrf_token, ENT_QUOTES, 'UTF-8') : ''; ?>">

<!-- Floating Background Visualizer -->
<div class="floating-visualizer">
  <div class="visualizer-circle" style="width: 300px; height: 300px; top: 10%; left: 10%;"></div>
  <div class="visualizer-circle" style="width: 200px; height: 200px; top: 60%; left: 70%;"></div>
  <div class="visualizer-circle" style="width: 400px; height: 400px; top: 30%; left: 50%;"></div>
</div>

<!-- Mini Player -->
<div id="miniPlayer" class="mini-player hidden">
  <i class="fas fa-play"></i>
</div>

<!-- Main Content -->
<div class="w-full max-w-2xl bg-gray-800 rounded-xl shadow-2xl overflow-hidden glass-effect">
  <!-- Header -->
  <div class="bg-gradient-to-r from-blue-600 to-purple-600 p-4 sm:p-6">
    <div class="flex flex-col sm:flex-row items-center justify-between">
      <h1 class="text-xl sm:text-2xl font-bold flex items-center neon-text mb-2 sm:mb-0">
        <i class="fas fa-broadcast-tower mr-2 sm:mr-3"></i>
        Local Radio FM
      </h1>
      <span class="live-indicator flex items-center bg-red-600 px-3 py-1 rounded-full text-xs font-semibold">
        <span class="w-2 h-2 bg-white rounded-full mr-1.5"></span>
        ON AIR
      </span>
    </div>
    <div class="song-info mt-3 sm:mt-4 p-3 sm:p-4 rounded-lg flex items-center">
      <div id="coverArt" class="w-12 h-12 rounded-md overflow-hidden default-cover" aria-label="Default cover art icon">
        <i class="fas fa-music text-xl text-purple-400" aria-hidden="true"></i>
      </div>
      <div class="ml-3 overflow-hidden" aria-live="polite">
        <div class="font-medium truncate" id="current-song" aria-label="Current song title">Select a song</div>
        <div class="text-xs text-blue-100 truncate" id="current-artist" aria-label="Current song artist">-</div>
      </div>
    </div>
  </div>

  <!-- Main Content -->
  <div class="p-4 sm:p-6">
    <!-- Audio Visualizer -->
    <div id="visualizer" class="audio-visualizer h-16 sm:h-24">
      <!-- Bars will be generated by JavaScript -->
    </div>
    <!-- Progress Bar -->
    <div class="progress-container w-full rounded-full mb-4">
      <div class="progress-bar" id="progress-bar"></div>
    </div>
    <!-- Audio Player -->
    <div class="flex flex-col items-center">
      <audio id="audio" controls class="w-full mb-4 rounded-lg hidden">
        <!-- Audio source will be set dynamically -->
      </audio>
      <!-- Custom Controls -->
      <div class="flex items-center justify-center space-x-2 sm:space-x-4 md:space-x-6 w-full mb-6">
        <button id="shuffleBtn" class="text-gray-400 hover:text-white p-2 sm:p-3 rounded-full" title="Shuffle" aria-label="Toggle shuffle mode">
          <i class="fas fa-random text-lg sm:text-xl" aria-hidden="true"></i>
        </button>
        <button id="prevBtn" class="text-gray-400 hover:text-white p-2 sm:p-3 rounded-full" title="Previous" aria-label="Previous song">
          <i class="fas fa-step-backward text-lg sm:text-xl" aria-hidden="true"></i>
        </button>
        <button id="playBtn" class="bg-green-600 hover:bg-green-700 text-white p-3 sm:p-4 rounded-full shadow-lg" title="Play/Pause" aria-label="Play or Pause music">
          <i class="fas fa-play text-lg sm:text-xl" aria-hidden="true"></i>
        </button>
        <button id="nextBtn" class="text-gray-400 hover:text-white p-2 sm:p-3 rounded-full" title="Next" aria-label="Next song">
          <i class="fas fa-step-forward text-lg sm:text-xl" aria-hidden="true"></i>
        </button>
        <button id="repeatBtn" class="text-gray-400 hover:text-white p-2 sm:p-3 rounded-full" title="Repeat" aria-label="Toggle repeat mode">
          <i class="fas fa-redo text-lg sm:text-xl" aria-hidden="true"></i>
        </button>
      </div>
      <!-- Volume Control -->
      <div class="flex items-center w-full mb-4 sm:mb-6">
        <i class="fas fa-volume-down text-gray-400 mr-2" aria-hidden="true"></i>
        <input type="range" id="volume" min="0" max="1" step="0.01" value="0.7"
               class="w-full h-1 bg-gray-600 rounded-lg appearance-none cursor-pointer" aria-label="Volume control">
        <i class="fas fa-volume-up text-gray-400 ml-2" aria-hidden="true"></i>
      </div>
      <!-- Time Display -->
      <div class="flex items-center justify-between w-full mt-3 sm:mt-4">
        <div class="flex items-center text-xs sm:text-sm text-gray-400">
          <i class="fas fa-clock mr-1 sm:mr-2"></i>
          <span>Current time:</span>
        </div>
        <div class="text-base sm:text-lg font-mono" id="current-time">00:00:00</div>
      </div>
      <!-- Duration -->
      <div class="flex items-center justify-between w-full mt-1 sm:mt-2">
        <div class="flex items-center text-xs sm:text-sm text-gray-400">
          <i class="fas fa-hourglass-half mr-1 sm:mr-2"></i>
          <span>Duration:</span>
        </div>
        <div class="text-base sm:text-lg font-mono" id="duration">00:00:00</div>
      </div>
      <!-- Stats -->
      <div class="grid grid-cols-3 gap-2 sm:gap-4 w-full mt-4 sm:mt-6 text-center">
        <div class="bg-gray-700 p-2 sm:p-3 rounded-lg">
          <div class="text-purple-400"><i class="fas fa-music"></i></div>
          <div class="text-xs text-gray-400">Type</div>
          <div class="font-bold" id="format">Audio</div>
        </div>
        <div class="bg-gray-700 p-3 rounded-lg">
          <div class="text-blue-400"><i class="fas fa-tachometer-alt"></i></div>
          <div class="text-xs text-gray-400">Bitrate</div>
          <div class="font-bold" id="bitrate">128 kbps</div>
        </div>
        <div class="bg-gray-700 p-3 rounded-lg">
          <div class="text-green-400"><i class="fas fa-headphones"></i></div>
          <div class="text-xs text-gray-400">Status</div>
          <div class="font-bold" id="status">Ready</div>
        </div>
      </div>
    </div>
  </div>

  <!-- Playlist Section -->
  <div class="w-full p-4 sm:p-6 bg-gray-800 border-t border-gray-700">
    <div class="flex flex-col sm:flex-row justify-between items-center mb-3 sm:mb-4">
      <h3 class="text-lg sm:text-xl font-bold" id="playlistTitle">Playlist</h3>
      <div class="flex gap-2 sm:gap-3 mt-2 sm:mt-0">
        <button id="refreshBtn" class="bg-white/10 px-2 py-1 sm:px-3 rounded-lg hover:bg-white/20 text-xs sm:text-sm" title="Refresh playlist" aria-label="Refresh playlist">
          <i class="fas fa-sync-alt" aria-hidden="true"></i> <span class="hidden sm:inline">Refresh</span>
        </button>
        <button id="uploadBtn" class="upload-btn px-3 py-1 sm:px-4 sm:py-2 rounded-lg text-white font-medium flex items-center text-xs sm:text-sm" title="Upload" aria-label="Open song upload modal">
          <i class="fas fa-upload mr-1 sm:mr-2" aria-hidden="true"></i>Upload
        </button>
      </div>
    </div>
    <div class="mb-3 sm:mb-4">
        <label for="searchInput" class="sr-only">Search Playlist</label> <!-- Screen-reader only label -->
        <input type="search" id="searchInput" name="searchInput"
               class="w-full bg-white/10 rounded-lg p-2 sm:p-3 focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/40 text-white text-sm sm:text-base"
               placeholder="Search by title or artist...">
    </div>
    <div class="playlist-container h-48 sm:h-64 overflow-y-auto pr-1 sm:pr-2">
      <ul id="playlist" class="space-y-2">
        <li class="text-center py-10 text-white/50">
          <i class="fas fa-music text-3xl mb-2"></i>
          <p>No songs in playlist</p>
        </li>
      </ul>
    </div>
  </div>

  <!-- Footer -->
  <div class="bg-gray-900 p-4 text-center text-xs text-gray-500">
    <p>© <span id="current-year"></span> Local Radio. All rights reserved.</p>
  </div>
</div>

<!-- Upload Modal -->
<div id="uploadModal" class="fixed inset-0 hidden items-center justify-center z-50 modal-overlay p-4" role="dialog" aria-modal="true" aria-labelledby="uploadModalTitle">
  <div class="glass-effect rounded-2xl p-4 sm:p-6 w-full max-w-md neon-shadow mx-auto">
    <div class="flex justify-between items-center mb-3 sm:mb-4">
      <h3 class="text-lg sm:text-xl font-bold" id="uploadModalTitle">Upload New Song</h3>
      <button id="cancelBtn" class="text-white/50 hover:text-white" aria-label="Close upload modal">
        <i class="fas fa-times text-lg sm:text-xl" aria-hidden="true"></i>
      </button>
    </div>
    <form id="uploadForm" class="space-y-3 sm:space-y-4" enctype="multipart/form-data">
      <div>
        <label for="titleInput" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Song Title</label>
        <input type="text" id="titleInput" name="title" required
               class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
               placeholder="Enter song title">
      </div>
      <div>
        <label for="artistInput" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Artist</label>
        <input type="text" id="artistInput" name="artist" required
               class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
               placeholder="Enter artist name">
      </div>
      <div>
        <label for="lyricsInput" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Lyrics (Optional)</label>
        <textarea id="lyricsInput" name="lyrics" rows="3"
                  class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
                  placeholder="Enter song lyrics"></textarea>
      </div>
      <div>
        <label class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Cover Art (Optional)</label>
        <div class="flex items-center gap-2 sm:gap-3">
          <label for="coverInput" class="cursor-pointer bg-white/10 rounded-lg p-2 sm:p-3 flex-1 text-center hover:bg-white/20 text-xs sm:text-sm">
            <i class="fas fa-image mr-1 sm:mr-2" aria-hidden="true"></i>
            <span id="coverFileName">Choose cover image</span>
          </label>
          <input type="file" id="coverInput" name="cover" accept="image/*" class="hidden">
          <div id="coverPreview" class="w-12 h-12 sm:w-16 sm:h-16 bg-white/5 rounded-lg overflow-hidden hidden flex-shrink-0">
            <img id="coverPreviewImg" class="w-full h-full object-cover" alt="Cover art preview">
          </div>
        </div>
      </div>
      <div>
        <label class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Song File (MP3, AAC, M4A, OGG)</label>
        <label for="songInput" class="cursor-pointer bg-white/10 rounded-lg p-2 sm:p-3 flex text-center hover:bg-white/20 text-xs sm:text-sm">
          <i class="fas fa-music mr-1 sm:mr-2" aria-hidden="true"></i>
          <span id="songFileName">Choose audio file</span>
        </label>
        <input type="file" id="songInput" name="song" accept="audio/mp3,audio/aac,audio/mp4,audio/ogg,.m4a" required class="hidden">
      </div>
      <div class="flex gap-2 sm:gap-4 pt-1 sm:pt-2">
        <button type="submit" class="flex-1 bg-white/10 px-3 py-2 sm:px-4 sm:py-3 text-xs sm:text-sm rounded-lg hover:bg-white/20 font-medium flex items-center justify-center" aria-label="Submit song upload">
          <i class="fas fa-cloud-upload-alt mr-1 sm:mr-2" aria-hidden="true"></i>Upload
        </button>
        <button type="button" id="cancelUploadBtn" class="flex-1 bg-red-500/20 px-3 py-2 sm:px-4 sm:py-3 text-xs sm:text-sm rounded-lg hover:bg-red-500/30 font-medium" aria-label="Cancel song upload">
          Cancel
        </button>
      </div>
    </form>
  </div>
</div>

<!-- Edit Song Modal -->
<div id="editSongModal" class="fixed inset-0 hidden items-center justify-center z-50 modal-overlay p-4" role="dialog" aria-modal="true" aria-labelledby="editSongModalTitle">
  <div class="glass-effect rounded-2xl p-4 sm:p-6 w-full max-w-md neon-shadow mx-auto">
    <div class="flex justify-between items-center mb-3 sm:mb-4">
      <h3 class="text-lg sm:text-xl font-bold" id="editSongModalTitle">Edit Song Details</h3>
      <button id="cancelEditSongBtn" class="text-white/50 hover:text-white" aria-label="Close edit modal">
        <i class="fas fa-times text-lg sm:text-xl" aria-hidden="true"></i>
      </button>
    </div>
    <form id="editSongForm" class="space-y-3 sm:space-y-4">
      <input type="hidden" id="editSongId" name="song_id">
      <div>
        <label for="editSongTitle" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Title</label>
        <input type="text" id="editSongTitle" name="title" required
               class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
               placeholder="Enter song title">
      </div>
      <div>
        <label for="editSongArtist" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Artist</label>
        <input type="text" id="editSongArtist" name="artist" required
               class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
               placeholder="Enter artist name">
      </div>
      <div>
        <label for="editSongLyrics" class="block mb-1 sm:mb-2 text-xs sm:text-sm font-medium">Lyrics</label>
        <textarea id="editSongLyrics" name="lyrics" rows="3 sm:rows-4"
                  class="w-full bg-white/10 rounded-lg p-2 sm:p-3 text-sm sm:text-base focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder-white/30"
                  placeholder="Enter song lyrics"></textarea>
      </div>
      <div class="flex gap-2 sm:gap-4 pt-1 sm:pt-2">
        <button type="submit" class="flex-1 bg-blue-600 hover:bg-blue-700 px-3 py-2 sm:px-4 sm:py-3 text-xs sm:text-sm rounded-lg font-medium flex items-center justify-center" aria-label="Save changes to song metadata">
          <i class="fas fa-save mr-1 sm:mr-2" aria-hidden="true"></i>Save Changes
        </button>
        <button type="button" id="closeEditSongModalBtn" class="flex-1 bg-red-500/20 px-3 py-2 sm:px-4 sm:py-3 text-xs sm:text-sm rounded-lg hover:bg-red-500/30 font-medium" aria-label="Cancel editing song">
          Cancel
        </button>
      </div>
    </form>
  </div>
</div>

<!-- Notification Toast -->
<div id="toast" role="alert" aria-live="assertive"></div>

<script src="/assets/js/main.min.js"></script>
</body>
</html>
